#Stage shebang script and GridFTP certificate to the node.
# # The executable itself will always be staged if the node is
# # on a different filesystem.
should_transfer_files = YES
transfer_input_files = /home/zrechav/SelfVeto_Correlation_Tables/scripts/air_shower_reader/AirShowerReader_NPX.sh
# # but do not try to copy outputs back (see: https://htcondor-wiki.cs.wisc.edu/index.cgi/tktview?tn=3081)
+TransferOutput=""

executable = /home/zrechav/SelfVeto_Correlation_Tables/scripts/air_shower_reader/AirShowerReader_NPX.sh

output = /scratch/zrechav/AirShowerReader/AirShowerReader_$(filenum).out
error = /scratch/zrechav/AirShowerReader/AirShowerReader_$(filenum).err
log = /scratch/zrechav/AirShowerReader/AirShowerReader_$(filenum).log

universe = vanilla
notification = never

#+AccountingGroup = "1_week.$ENV(USER)"
#+AccountingGroup="uwa.$ENV(USER)"
Requirements = (OpSysMajorVer == 7 || OSGVO_OS_VERSION == 7)
+SingularityImage="/cvmfs/singularity.opensciencegrid.org/opensciencegrid/osgvo-el7:latest"
request_memory = 8000
#request_memory = (NumJobStarts is undefined) ? 2 * pow(2, 10) : 2048 * pow(2, NumJobStarts + 1)
periodic_release = (HoldReasonCode =?= 21 && HoldReasonSubCode =?= 1001) || HoldReasonCode =?= 21
periodic_remove = (JobStatus =?= 5 && (HoldReasonCode =!= 34 && HoldReasonCode =!= 21)) || (RequestMemory > 13192)

arguments = $(infile) $(outfile)  

queue
